### ISSUE TITLE
Regex filters are unneessarily complicated

### ISSUE THREAD

**Issue by DL6ER** [mmotti/pihole-regex#1]
I see you're having many lines like
```
^((.*)(1stok\.com))$
```

Why don't you write this filter in the much simpler form?
```
1stok\.com$
```

---

Similarly,
```
^((ad\.)(.*))$
```
could just be
```
^ad\.
```
to match anything that starts in `ad.`

Although the regex compiler in *FTL*DNS will take care of simplifying filters as much as possible, it can only be beneficial to already provide simple filters and don't rely on the simplifier in cases where this is not necessary. It would also make your list much more readable.

**Comment by mmotti** [comment]
I agree - They are a little over complicated for this task.

The reason being that I had quickly re-used an existing function to generate these, where it was previously necessary to be able to extract from specific groups.

I will look at simplifying them.

**Comment by DL6ER** [comment]
Yeah, I think this is an improvement. Thanks.
