### ISSUE TITLE
^telemetry[-.]  doesn't block all telemetry sites

### ISSUE THREAD

**Issue by eejeel** [mmotti/pihole-regex#10]
The option  ^telemetry[-.]  doesn't block sites like:

reports.wes.df.telemetry.microsoft.com
services.wes.df.telemetry.microsoft.com
sqm.df.telemetry.microsoft.com
sqm.telemetry.microsoft.com
sqm.telemetry.microsoft.com.nsatc.net
telecommand.telemetry.microsoft.com
telecommand.telemetry.microsoft.com.nsatc.net
watson.telemetry.microsoft.com
watson.telemetry.microsoft.com.nsatc.net
etc.

Beter is to use
(^|\.)telemetry[-.]
which also covers the examples above.

**Comment by mmotti** [comment]
Made a change to reflect this in https://github.com/mmotti/pihole-regex/commit/3b38c283493cad8d99449f8dd2f46c3050661e7e
