### ISSUE TITLE
Blocks Twitch.tv stream servers

### ISSUE THREAD

**Issue by jacklul** [mmotti/pihole-regex#15]
`^(.+[-_.])??m?ad[sxv]?[0-9]*[-_.]` blocks servers, especially `video-edge-c2a2dc.mad01.abs.hls.ttvnw.net`.
Impossible to whitelist as there is no wildcard whitelisting currently and there is a lot of various strings before `mad01`.

**Comment by mmotti** [comment]
Hi,

Apologies for the delay.

Thank-you for reporting this. I was considering altering the regexp so it would have to start with `ads.` or `mads.`, rather than allowing it to appear as a subdomain, but for now I will simply remove the possibility to match `mads.`
