### ISSUE TITLE
sqlite3.OperationalError

### ISSUE THREAD

**Issue by malbul** [mmotti/pihole-regex#17]
Hello!

Looks like DB structure has changed.

Anyway, thank you for this script and the hard work you have done. :)

```shell
root@pihole:~# curl -sSl https://raw.githubusercontent.com/mmotti/pihole-regex/master/install.py | sudo python3
[i] Root user detected
[i] Pi-hole path exists
[i] DB detected
[i] Fetching: https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list
[i] 16 regexps collected from https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list
[i] Connecting to /etc/pihole/gravity.db
[i] Adding / updating regexps in the DB
Traceback (most recent call last):
  File "<stdin>", line 108, in <module>
sqlite3.OperationalError: near "ON": syntax error
root@pihole:~#
```

**Comment by mmotti** [comment]
Hey :)

Are you on the latest version of pihole? I only tested this then other day
and it worked okay on my end.

They have made changes in recent versions; adding extra columns to the
tables etc

pihole -up

**Comment by malbul** [comment]
Sorry, I forgot to mention that I am using the `dev` version of the `pi-hole`:

**Pi-hole Version vDev** (development, v4.3.2-359-g8d5d423)
**Web Interface Version vDev** (devel, v4.3.2-264-g34d92ad)
**FTL Version vDev** (development, vDev-bb9f25c)

```shell
root@pihole:~# sqlite3 --version
3.22.0 2018-01-22 18:45:57 0c55d179733b46d8d0ba4d88e01a25e10677046ee3da1d5b1581e86726f2alt1
```

Probably this is not an issue, sorry, I have realized it only when you asked me about the version. :)

**Comment by mmotti** [comment]
Ah, that's it - Because I've used the 'upsert' syntax you need at least version 3.24 of SQLite :)

Dev branch pihole is fine

**Comment by mmotti** [comment]
To avoid issues with this in future, I have updated the script to add support for an alternative query for sqlite3 versions < 3.24: https://github.com/mmotti/pihole-regex/commit/d8066b6a6ee9ef11669cd6a0d8dc098452a819bd

If you try run the script again it should hopefully work for you :-)

**Comment by malbul** [comment]
Yep, now it works for me, thanks for the quick fix. :)

```shell
root@pihole:~# curl -sSl https://raw.githubusercontent.com/mmotti/pihole-regex/master/install.py | sudo python3
[i] Root user detected
[i] Pi-hole path exists
[i] DB detected
[i] Fetching: https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list
[i] 16 regexps collected from https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list
[i] Connecting to /etc/pihole/gravity.db
[i] Adding / updating regexps in the DB
[i] Identifying obsolete regexps
[i] Restarting Pi-hole
[i] Done - Please see your installed regexps below

^(.+[-_.])??ad[sxv]?[0-9]*[-_.]
^(.+[-_.])??adse?rv(er?|ice)?s?[0-9]*[-.]
^(.+[-_.])??telemetry[-.]
^adim(age|g)s?[0-9]*[-_.]
^adtrack(er|ing)?[0-9]*[-.]
^advert(s|is(ing|ements?))?[0-9]*[-_.]
^aff(iliat(es?|ion))?[-.]
^analytics?[-.]
^banners?[-.]
^beacons?[0-9]*[-.]
^count(ers?)?[0-9]*[-.]
^pixels?[-.]
^stat(s|istics)?[0-9]*[-.]
^track(ers?|ing)?[0-9]*[-.]
^traff(ic)?[-.]
^xn--
```

**Comment by mmotti** [comment]
No probs! 👍
