### ISSUE TITLE
ad.nl is blocked

### ISSUE THREAD

**Issue by woftor** [mmotti/pihole-regex#20]
A news website in the Netherlands is blocked by the first regex. It is ad.nl / www.ad.nl.

`^(.+[_.-])?ad[sxv]?[0-9]*[_.-]`

I tried white listing, but then it loads the website only partially. Is there anything you can do to make the regex so, that this website is not blocked?

**Comment by mmotti** [comment]
I will take a look at what can be done :)

**Comment by mmotti** [comment]
@woftor did you whitelist both `ad.nl` and `www.ad.nl`? Also, what version of Pi-hole are you running?

Pi-hole v5 is currently in beta and that version implements regex whitelisting. This basically means that once it's stable and released to the masses, you will be able to add the following regex whitelist entry `^(.+\.)?ad\.nl$` to unblock `ad.nl` and all of it's subdomains.

**Comment by woftor** [comment]
> @woftor did you whitelist both `ad.nl` and `www.ad.nl`? Also, what version of Pi-hole are you running?
> 
> Pi-hole v5 is currently in beta and that version implements regex whitelisting. This basically means that once it's stable and released to the masses, you will be able to add the following regex whitelist entry `^(.+\.)?ad\.nl$` to unblock `ad.nl` and all of it's subdomains.

I switched to the beta 5.0 and added your whitelost regex. It is working sir! Thanks!

**Comment by mmotti** [comment]
Good news! Glad to hear :-)
