### ISSUE TITLE
Maybe "traff(ic)" is a bit broad?

### ISSUE THREAD

**Issue by simonjosefsson** [mmotti/pihole-regex#21]
Found that "^traff(ic)?[.-]" blocked some feeds (e.g traffic.libsyn.com and traffic.omny.fm) in my podcast app.
Didn't realize that pi-hole was the culprit until I noticed those podcasts suddenly updating when connected to a different network

Sure, it's easy enough to whitelist but maybe "traffic" causes to many false positives?
What is the rationale of blocking it?

I'd accept if this issue is closed without changes, just thought I'd bring this to your attention.

**Comment by mmotti** [comment]
The majority of there were compiled from patterns that occurred in
blocklists.

If this one or another is too temperamental then I'm happy to remove or
substitute it :)

Will take a look.

**Comment by mmotti** [comment]
I have removed the traffic regexp as I agree it's potentially a little too broad :-)

Depending on how you installed the regexps, you can either remove manually or run the installer again to process this change.
