### ISSUE TITLE
regex.list breaks torrents

### ISSUE THREAD

**Issue by Dustie** [mmotti/pihole-regex#24]
This regex:
`^track(ers?|ing)?[0-9]*[_.-]`

breaks a lot of bittorrent trackers.

"tracker.hostname.com"

**Comment by mmotti** [comment]
Thanks for reporting! I will look at adjusting this

**Comment by mmotti** [comment]
Please see: https://github.com/mmotti/pihole-regex/commit/acf9a5be5921cc2c58cfe9958e163f19cc908fe3

Although as a word of warning, if Pi-hole is blocking torrents from being downloaded then you probably aren't sitting behind a VPN which isn't great.
