### ISSUE TITLE
False positive ad.nl

### ISSUE THREAD

**Issue by Botros84** [mmotti/pihole-regex#25]
^(.+[_.-])?ad[sxv]?[0-9]*[_.-] - gives a false positive on dutch newspaper website ad.nl

**Comment by mmotti** [comment]
Hi mate,

Sadly this is one of the few examples of legitimate sites that get caught in that filter.

The solution to this is here: https://github.com/mmotti/pihole-regex/issues/20

In summary, in Pihole v5 you can use regex whitelists and you can whitelist ad.nl and all subdomains.

**Comment by Botros84** [comment]
Hi Mmotti

Thanks for the heads up and apologies for a double comment on that.

-- Best regards,
Orwell84



Op do 26 mrt. 2020 om 23:32 schreef mmotti <notifications@github.com>:

**Comment by mmotti** [comment]
No problem :-) this is the only legitimate site I've come across so far that is picked up by that regexp though.

**Comment by sjhgvr** [comment]
ad.st
Redirect to angeldu.st
