### ISSUE TITLE
False positive on all IDN domains

### ISSUE THREAD

**Issue by gjherbiet** [mmotti/pihole-regex#26]
The blacklist regex entry ``^(www[0-9]*\.)?xn--`` will falsely block all [IDN domains](https://en.wikipedia.org/wiki/Internationalized_domain_name) as their internal [Punycode](https://en.wikipedia.org/wiki/Punycode) representation in the DNS starts with the ``xn--`` LDH label (see [RFC 5890](https://tools.ietf.org/html/rfc5890)).

I know IDN domains are used for [homograph attacks](https://en.wikipedia.org/wiki/IDN_homograph_attack), but it seems quite harsh to blacklist all IDNs as many of them are legit and registered in good faith.

Besides, this would result in all domains registered in languages not using a latin alphabet to be blacklisted by the mentioned regex.

**Comment by mmotti** [comment]
Hi,

This was initially included as from my perspective (being based in the UK), I had no need for these domains to be accessible and I hadn't foreseen how many people from different locations would end up using this list.

I will at some point look to perhaps separate out this entry into an 'optional' list.

**Comment by mmotti** [comment]
Please see https://github.com/mmotti/pihole-regex/commit/90e765571e63409fd975f88374fa46a51917a31b
