### ISSUE TITLE
Regex doesn't capture all FB sites

### ISSUE THREAD

**Issue by eejeel** [mmotti/pihole-regex#28]
^([^.]+\.)?(facebook|fb(cdn|sbx)?|tfbnw)\.[^.]+$
This doesn't capture sites like 0.channel15.facebook.com and 1000068744-facebook.com and there are more.
Solution: ^(.+[_.-])?(facebook|fb(cdn|sbx)?|tfbnw)\.[^.]+$

The same kind of problem is for the both user suggested regex
Replace ^([^.]+\.)?  by  ^(.+[_.-])?

**Comment by mmotti** [comment]
Hi,

Good catch! I had overlooked the possibility of multiple subdomains when putting these together.

I don't think it's 100% necessary to include the underscore and hyphen in the character set for these examples (going by the blacklist domains that I've seen for FB), but I have done so to keep it consistent for now.

Thanks for reporting!
