### ISSUE TITLE
False positive: ad.st (Redirect to angeldu.st)

### ISSUE THREAD

**Issue by sjhgvr** [mmotti/pihole-regex#29]
Matched by:  `^(.+[_.-])?ad([sxv]?[0-9]*|system)[_.-]`
Suggested fix: `^(.+[_.-])?ad([sxv]?[0-9]*|system)[_.-]*\..*\.` (this also fixes the ad.nl issue.)

Credits go to the CEO of Metagaming B.V. for finding this FP and contacting me about it.

**Comment by mmotti** [comment]
Hey!

Thanks for reporting this; I hadn't realised quite how widespread this issue could be.

I tried your suggested regexp but sadly this would not match sites like **amazon-adsystem.com**

The easiest way I could think to achieve what we're looking for is as follows: 

`^ad([sxv]?[0-9]*|system)[_.-]([^.[:space:]]+\.){1,}|^.+[_.-]ad([sxv]?[0-9]*|system)[_.-]`

This basically means that if the string starts with something like **ad.**, it must follow with at least one further dot, therefore excluding domains such as ad.nl.

I couldn't think of a way to incorporate this into a single statement whilst still capturing the required domains, so it's basically two options for both domain and subdomains.

It looks to work OK on my end but welcome feedback.

**Comment by sjhgvr** [comment]
Perfect :)
