### ISSUE TITLE
www.iij.ad.jp & iij.ad.jp - regex conflicts.

### ISSUE THREAD

**Issue by badmojr** [mmotti/pihole-regex#32]
From https://public.dns.iij.jp/. (DoH/DoT service)
Link to their privacy policy blocked i.e https://www.iij.ad.jp/privacy/

**Comment by mmotti** [comment]
Hi,

I have added these to the false positive domain list.

If this becomes too much of an issue in future I'll try to see if there's any way to adapt some of the regular expressions but it'll likely mean that I need to split them up a bit.

Cheers!
