### ISSUE TITLE
AdGuard Home Syntax Support for regex.list

### ISSUE THREAD

**Issue by hl2guide** [mmotti/pihole-regex#34]
Please consider creating an AdGuard Home Syntax version for **regex.list.**

(see https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#regular-expressions)

Essentially it needs each regex to start and end with a / character.

**Comment by mmotti** [comment]
It already exists [here](https://raw.githubusercontent.com/mmotti/adguard-home-filters/master/regex.txt)

:-)
