### ISSUE TITLE
Regex for blocking all of twitter

### ISSUE THREAD

**Issue by mettacrawler** [mmotti/pihole-regex#36]
`^(.+[_.-])?(twitter|twimg|cms-twdigitalassets)\.(co\.)?[^.]+$`

Handles

```
twitter.co.uk
twitter.co.in
cdn.cms-twdigitalassets.com
twitter.com
pbs.twimg.com
anything.twitter.com
any.thing.twitter.com
```

**Comment by mmotti** [comment]
Thank you! I will look at this next time my laptop is on.

I think this will be another one where the accommodation for .co is
unnecessary though as again they all seem to redirect to the parent domain
:)

**Comment by mmotti** [comment]
Please see https://github.com/mmotti/pihole-regex/commit/77e7074f5eb8fca67e75493b4c251f0cfd9ba229
