### ISSUE TITLE
Installation not working due to "{path_pihole} was not found"

### ISSUE THREAD

**Issue by Darth-Igi** [mmotti/pihole-regex#37]
In install.py in line 39 is the follwing written: path_pihole = r'/etc/pihole'.
The "r" causes an error and breaks the installation.

I removed the "r" and run the script locally without any error.

**Comment by mmotti** [comment]
That's interesting - I have never heard of that one before.

What is your Python version? The `r` is simply saying to treat the directory as a literal string so as to treat the backslashes as backslashes.

**Comment by Darth-Igi** [comment]
I believe that :-)
I used the current version 3.9.0.

**Comment by mmotti** [comment]
Thanks for confirming - My test installation (Ubuntu Server) is @ 3.8.3 i think.

Will try update it to 3.9 and see if I can replicate this but I am not hopeful as I wouldn't have thought they'd have messed around with the literal strings.

Do you know specifically what error occurs?

Cheers!
