### ISSUE TITLE
How to install when running Pi-hole in a container (set up in portainer)?

### ISSUE THREAD

**Issue by jonschlu** [mmotti/pihole-regex#38]
The script will obviously not work in this case, as the /etc/pihole. How would one be able to use this script in this case?

**Comment by talondnb** [comment]
https://www.reddit.com/r/pihole/comments/ir6jdk/possible_to_add_regex_list_as_adlist/

**Comment by mmotti** [comment]
Hi,

I don't have experience as such with Portainer (or even really docker until the last few hours), but I have just added some support for pihole running in the default docker configuration as listed [here](https://hub.docker.com/r/pihole/pihole).

Essentially the changes are as follows:
1. Look for an active docker container with the name of **pihole** (`docker ps --filter name=pihole -q`)
2. Using the Container ID of the above, find the mounts using `docker inspect`
3. Obtain the source mount location where the destination mount is `/etc/pihole` (e.g.  `/home/mmotti/test/etc-pihole`)
4. Prefix pihole restart commands with `docker exec -it pihole`

To save me a little time with research, are you able to outline at all any changes that may need to be added to make Portainer compatible? e.g. Do I need to provide the user with the ability to specify a container name, are you able to still use docker exec to restart pihole etc?

**Comment by mmotti** [comment]
Closing for now until more information becomes available
