### ISSUE TITLE
Doesn't work - syntax error

### ISSUE THREAD

**Issue by oywino** [mmotti/pihole-regex#39]
When I run the command specified:
`curl -sSl https://raw.githubusercontent.com/mmotti/pihole-regex/master/install.py | sudo python3`

This is the result:

`File "<stdin>", line 100
print(f'[e] {path_pihole} was not found')
SyntaxError: invalid syntax`

I'm running Pi-Hole 5.2.1 in a docker container.

**Comment by mmotti** [comment]
Sorry to hear that you're having trouble - What is your python version?

**Comment by oywino** [comment]
phython3 -V returns:
`Python 3.6.12`

**Comment by mmotti** [comment]
That's really odd - it looks like it has an issue with the f string which
I'm fair certain was introduced in python 3.6.

Have your tried a slightly later version or python? 3.7+?

**Comment by oywino** [comment]
What's the easiest way to upgrade Python?

**Comment by mmotti** [comment]
If you're running Raspbian, this looks pretty straight forward:

https://installvirtual.com/how-to-install-python-3-8-on-raspberry-pi-raspbian/

**Comment by oywino** [comment]
Quite interesting - if I type:
`pyton3 -V`
I get:
`Python 3.6.12`

But if I type:
`python3.8 -V`
I get:
`Python 3.8.6`

So how do I know which on is being used? (and why do I have both?)

**Comment by mmotti** [comment]
I must admit I'm not really a wiz with Linux but I would assume that you need to update your local path to point Python to the newer version.

What happens when you try 

`curl -sSl https://raw.githubusercontent.com/mmotti/pihole-regex/master/install.py | sudo python3.8`

**Comment by oywino** [comment]
This is what I got:
`[i] Checking for "pihole" docker container                                                                                                               
[i] Running in physical installation mode                                                                                                                
[i] Pi-hole path exists                                                                                                                                  
[i] Write access to /etc/pihole verified                                                                                                                 
[i] DB detected                                                                                                                                          
[i] Fetching: https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list                                                                    
[i] 14 regexps collected from https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list                                                    
[i] Connecting to /etc/pihole/gravity.db                                                                                                                 
[i] Adding / updating regexps in the DB                                                                                                                  
[i] Identifying obsolete regexps                                                                                                                         
[i] Restarting Pi-hole                                                                                                                                   
[i] Done - Please see your installed regexps below

(\.|^)ab\.adnxs\.com$                                                                                                                                    
(\.|^)adnxs\.com$                                                                                                                                        
(\.|^)advertisement\.file\.no$                                                                                                                           
(\.|^)aic\.essrtb\.com$                                                                                                                                  
(\.|^)ajax\.googleapis\.com$                                                                                                                             
(\.|^)am\.medialaben\.no$                                                                                                                                
(\.|^)b141\.s407\.meetrics\.net$                                                                                                                         
(\.|^)connect\.facebook\.net$                                                                                                                            
(\.|^)d1z2jf7jlzjs58\.cloudfront\.net$                                                                                                                   
(\.|^)digi\.static\.gfx\.no$                                                                                                                             
(\.|^)fra1-ib\.adnxs\.com$                                                                                                                               
(\.|^)g\.doubleclick\.net$  
(\.|^)ib\.adnxs\.com$                                                                                                                                    
(\.|^)maptiles\.finncdn\.no$                                                                                                                             
(\.|^)p\.lp4\.io$                                                                                                                                        
(\.|^)pagead2\.googlesyndication\.com$                                                                                                                   
(\.|^)polyfill\.spinnaker-js\.com$                                                                                                                       
(\.|^)s0\.2mdn\.net$                                                                                                                                     
(\.|^)s1\.adform\.net$                                                                                                                                   
(\.|^)sb\.scorecardresearch\.com$                                                                                                                        
(\.|^)script\.hotjar\.com$                                                                                                                               
(\.|^)securepubads\.g\.doubleclick\.net$                                                                                                                 
(\.|^)snap\.licdn\.com$                                                                                                                                  
(\.|^)srv-2020-07-06-08\.pixel\.parsely\.com$                                                                                                            
(\.|^)www\.facebook\.com$                                                                                                                                
(^|\.)acdn\.adnxs\.com$                                                                                                                                  
(^|\.)ams1-ib\.adnxs\.com$
(^|\.)avast\.com$                                                                                                                                        
(^|\.)cm\.g\.doubleclick\.net$                                                                                                                           
(^|\.)d5p\.de17a\.com$                                                                                                                                   
(^|\.)ib\.adnxs\.com$                                                                                                                                    
(^|\.)pp\.lp4\.io$                                                                                                                                       
(^|\.)sb\.scorecardresearch\.com$                                                                                                                        
(^|\.)smartadserver\.com$                                                                                                                                
(^|\.)vcdn\.adnxs\.com$                                                                                                                                  
^(.+[_.-])?adse?rv(er?|ice)?s?[0-9]*[_.-]                                                                                                                
^(.+[_.-])?telemetry[_.-]                                                                                                                                
^ad([sxv]?[0-9]*|system)[_.-]([^.[:space:]]+\.){1,}|[_.-]ad([sxv]?[0-9]*|system)[_.-]                                                                    
^adim(age|g)s?[0-9]*[_.-]                                                                                                                                
^adtrack(er|ing)?[0-9]*[_.-]                                                                                                                             
^advert(s|is(ing|ements?))?[0-9]*[_.-]                                                                                                                   
^aff(iliat(es?|ion))?[_.-]                                                                                                                                    
^analytics?[_.-]                                                                                                                                         
^banners?[_.-]                                                                                                                                           
^beacons?[0-9]*[_.-]                                                                                                                                     
^count(ers?)?[0-9]*[_.-]                                                                                                                                 
^mads\.                                                                                                                                                  
^pixels?[-.]                                                                                                                                             
^stat(s|istics)?[0-9]*[_.-]                                                                                                                              
c1.adform.net`

**Comment by mmotti** [comment]
Hm that's interesting - it looks like it found a local database and put the
entries inside of it (i.e /etc/pihole)

What is the output of the following?

docker ps --filter name=pihole -q

**Comment by oywino** [comment]
Nothing.
Remember I'm not running Pi-Hole in a docker container, but in an LXC container.

**Comment by mmotti** [comment]
Ah sorry I don't have much experience with containers.

Do the regexps show correctly as part of your pihole installation? If you
can see them in the web administration page, you should be good to go

**Comment by oywino** [comment]
Sorry, I do not know where to look. Please guide me.

**Comment by mmotti** [comment]
If you login to the admin area (if you installed it) - e.g mine was
192.168.1.2/admin

They should be in the blacklist area somewhere. I'm not too familiar with
pihole and the exact placement of things atm

**Comment by oywino** [comment]
Yes, I found them all.
Do you have a URL I can visit to check if these entries are in effect ?

**Comment by mmotti** [comment]
something like ads.bbc.co.uk or something should work. If you check the
logs it will hopefully say blocked by a regexp.

**Comment by oywino** [comment]
Yes, working fine.
But isn't it a bit too restrictive to block all of Facebook?  I'm not so sure my wife and daughter will be very happy about that 😉

**Comment by mmotti** [comment]
Facebook is optional :) it's not included in my install script.

It's for those who don't like Facebook haha
