### ISSUE TITLE
commands for cronjob error

### ISSUE THREAD

**Issue by plehmann1** [mmotti/pihole-regex#41]
when pasting this into the shell,  Pihole returns an error.

SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
30 2 * * 1 /usr/bin/curl -sSl https://raw.githubusercontent.com/mmotti/pihole-regex/master/install.py | /usr/bin/python3

error is:
-bash: 30: command not found
 
presume user error or is this an error in the script ? on the instructions located at 

https://github.com/mmotti/pihole-regex

**Comment by dflock** [comment]
You don't paste that one into the shell - that stuff goes into the crontab
so that thing's get updated automatically.

**Comment by mmotti** [comment]
As @dflock mentioned, you should paste these into the crontab window.

However, this step is not entirely necessary as the regexps don't get updated too often. If you like, you can just check back every few months and run the install command again manually :-)

**Comment by plehmann1** [comment]
thx for the reply mmotti :)
