### ISSUE TITLE
Project lacks license

### ISSUE THREAD

**Issue by tryoxiss** [mmotti/pihole-regex#68]
This repository/project does not have a license assosiated with it (that I can find), so functionally nobody is able to legally use these lists. Consider adding a license to this repository, for something small and simple like this I would reccommend CC0 (public domain) and MIT-0 for people who hate the idea of CC0 for software-adjacent things. If you don't like the idea of public domain the MIT licence is great.

**Comment by mmotti** [comment]
I will look into it. I've stepped away from Pihole related stuff as I don't use DNS level adblockers anymore but it's always been the intention that anyone can do whatever they like with the code :)
