### ISSUE TITLE
Twitch streams mistakenly blocked

### ISSUE THREAD

**Issue by ArniDagur** [mmotti/pihole-regex#9]
The domain `video-edge-6ea608.mrs01.abs.hls.ttvnw.net`, used to deliver TwitchTV livestreams was blocked, which caused the livestream I was watching to not load. Whitelisting it fixed the issue.

**Comment by mmotti** [comment]
Hi,

Sorry for the delay in my response.

This domain would not be caught by any of the regexps in this list. I ran a quick check to verify this:

```
Testing 16 regexps against video-edge-6ea608.mrs01.abs.hls.ttvnw.net

0 regexps matched video-edge-6ea608.mrs01.abs.hls.ttvnw.net
```

I would suggest that this must be an issue with a different regexp, blocklist or wildcard :-)
